{% set name = "tensorflow-datasets" %}
{% set version = "4.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1b3b2ead11fe7a43b137c1df13c1c5937f7cab54def9e966390c3638b3f38278

build:
  number: 0
  noarch: python
  entry_points:
    - tfds = tensorflow_datasets.scripts.cli.main:launch_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - absl-py
    - attrs >=18.1.0
    - dataclasses
    - dill
    - future
    - importlib_resources
    - numpy
    - promise
    - protobuf >=3.12.2
    - python >=3.6
    - requests >=2.19.0
    - six 1.15.*
    - tensorflow-metadata
    - tensorflow >=2.1
    - termcolor
    - tqdm
    - typing-extensions ==3.7.4

test:
  imports:
    - tensorflow_datasets
    - tensorflow_datasets.audio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-datasets/
  summary: tensorflow/datasets is a library of datasets ready to use with TensorFlow.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
