{% set name = "tensorflow-datasets" %}
{% set version = "4.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/datasets/archive/refs/tags/v{{ version }}.zip
  sha256: 7dbf6bfe5ee5e4d627cf8fc560069ec48cfa8f6163f4d13f1a822c20166ce105

build:
  number: 0
  noarch: python
  entry_points:
    - tfds = tensorflow_datasets.scripts.cli.main:launch_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - absl-py >=1
    - dill
    - etils
    - zipp
    - numpy
    - promise
    - protobuf >=3.12.2
    - requests >=2.19.0
    - wrapt
    - tensorflow-metadata
    - termcolor
    - toml
    - tqdm
    - typing-extensions
    - importlib_resources
    - tensorflow >=2
    - python >=3.7
    - click
    - psutil
    - dm-tree

test:
  imports:
    - tensorflow_datasets
    - tensorflow_datasets.audio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-datasets/
  summary: tensorflow/datasets is a library of datasets ready to use with TensorFlow.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
    - ngam
