{% set name = "tensorflow-datasets" %}
{% set version = "4.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 476f8c45354db62ece48aa12e7f73152ca077c5a5ee8a42980faeb8445fb6e26

build:
  number: 0
  noarch: python
  entry_points:
    - tfds = tensorflow_datasets.scripts.cli.main:launch_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - absl-py
    - attrs >=18.1.0
    - dataclasses
    - dill
    - future
    - importlib_resources
    - numpy
    - promise
    - protobuf >=3.12.2
    - python >=3.6
    - requests >=2.19.0
    - six 1.15.*
    - tensorflow-metadata
    - tensorflow >=2.1
    - termcolor
    - tqdm
    - typing-extensions

test:
  imports:
    - tensorflow_datasets
    - tensorflow_datasets.audio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorflow-datasets/
  summary: tensorflow/datasets is a library of datasets ready to use with TensorFlow.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
